In [1]:
'''
Importing the required Libraries
Importing the data set
Handling the Missing Data.
Encoding Categorical Data.
Splitting the data set into test set and training set.
Feature Scaling.
'''

import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/afrozchakure/Internity-Summer-Internship-Work/master/Blogs/Preprocessing/Data.csv')

In [2]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [4]:

#Idependednt
X = df.iloc[:, :-1].values
#dependent
y = df.iloc[:, 3].values

print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [5]:
#Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder
encoded = LabelEncoder()
X[:,0] = encoded.fit_transform(X[:,0])
print(X)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 nan]
 [0 35.0 58000.0]
 [2 nan 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [8]:
#Handling missing values

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean")

In [9]:
imputer.fit(X[:, 1:3])

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [10]:
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [11]:
#Splitting data into training and test
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split( X , y , test_size = 0.2, random_state = 0)

In [12]:
#Feature scaling

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [13]:
print(X_train)

[[-1.          2.64575131 -0.77459667  0.25315802         nan]
 [ 1.         -0.37796447 -0.77459667 -0.23014365  0.44897083]
 [-1.         -0.37796447  1.29099445 -1.84114924 -1.41706417]
 [-1.         -0.37796447  1.29099445         nan -1.0242147 ]
 [ 1.         -0.37796447 -0.77459667  1.54196248  1.62751925]
 [-1.         -0.37796447  1.29099445 -0.0690431  -0.14030338]
 [ 1.         -0.37796447 -0.77459667  0.89756025  0.94003267]
 [ 1.         -0.37796447 -0.77459667 -0.55234477 -0.43494049]]


In [14]:
print(X_test)

[[-1.          2.64575131 -0.77459667 -1.35784756 -0.82778996]
 [-1.          2.64575131 -0.77459667  1.8641636   2.02036872]]
